package com.mobilemacrofarm.state;

public enum MacroState {
    IDLE, ALIGNING, FARMING, SHIFTING_LANE, RESTARTING,
    RECORDING, REPLAYING,
    WAITING_FOR_DESK, DESK_DELAY, WAITING_FOR_PLOT, PEST_FLY_UP, PEST_HUNTING, PEST_ONLY_MODE
}
